version: 0.0
os: linux

files:
  - source: index.php
    destination: /var/www/html

permissions:
  - object: /var/www/html
    pattern: index.php
    mode: 755
    type:
      - file

hooks:
  BeforeInstall: 
    - location: scripts/cleanup.sh